system:
  chunk_size: 1000
  chunk_overlap: 200
  embedding_model: "Alibaba-NLP/gte-base-en-v1.5"
  embedding_dimension: 768
  llm_model: "llama-3.3-70b-versatile"
  similarity_threshold: 0.5
  device: "cpu"

paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  vector_index: "data/vector_store/index.faiss"
